/** Centralized, typed TanStack Query keys. */
export const queryKeys = {
  session: ['session'] as const,
  organizations: ['organizations'] as const,
  team: ['team'] as const,
  overview: ['analytics', 'overview'] as const,
  activity: ['analytics', 'activity'] as const,
  briefing: ['ai', 'briefing'] as const,
  assistantSeed: ['ai', 'assistant-seed'] as const,
  wallets: ['wallets'] as const,
  wallet: (id: string) => ['wallets', id] as const,
  agents: ['agents'] as const,
  agent: (id: string) => ['agents', id] as const,
  policies: ['policies'] as const,
  policy: (id: string) => ['policies', id] as const,
  budgets: ['budgets'] as const,
  budget: (id: string) => ['budgets', id] as const,
  transactions: ['transactions'] as const,
  transaction: (id: string) => ['transactions', id] as const,
  proposals: ['proposals'] as const,
  proposal: (id: string) => ['proposals', id] as const,
  memory: ['memory'] as const,
  memoryRecord: (id: string) => ['memory', id] as const,
  rates: ['rates'] as const,
  notifications: ['notifications'] as const,
  apiKeys: ['developer', 'keys'] as const,
  webhooks: ['developer', 'webhooks'] as const,
};
