import type { AgentCredential } from './types';

export const MOCK_CREDENTIALS: AgentCredential[] = [
  {
    id: 'cred-101',
    name: 'Horizon Testnet RPC Bearer Token',
    type: 'bearer_token',
    service: 'Stellar Horizon RPC',
    assignedAgentId: 'agt-soroban-relayer',
    assignedAgentName: 'Soroban Relayer Sentinel',
    maskedValue: 'astroid_tok_live_••••••••••••89fa',
    rawSecret: 'astroid_tok_live_88f291039aa89fa',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    lastAccessedAt: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    lastRotatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    status: 'active',
  },
  {
    id: 'cred-102',
    name: 'Nvidia NIM Financial Model API Key',
    type: 'api_key',
    service: 'Nvidia NIM AI Engine',
    assignedAgentId: 'agt-nim-briefing',
    assignedAgentName: 'Nvidia NIM Analyst Agent',
    maskedValue: 'nvapi-••••••••••••••••331b',
    rawSecret: 'nvapi-890218930182390183918331b',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    lastAccessedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    lastRotatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    status: 'active',
  },
  {
    id: 'cred-103',
    name: 'CoinGecko Oracle Webhook Secret',
    type: 'webhook_secret',
    service: 'CoinGecko Price Oracle',
    assignedAgentId: 'agt-amm-arb',
    assignedAgentName: 'Soroban DEX Arbitrageur',
    maskedValue: 'whsec_••••••••••••771c',
    rawSecret: 'whsec_892018391823771c',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    lastAccessedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    lastRotatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    status: 'active',
  },
];
