import type { AuditEvent } from './types';

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'evt-1001',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    eventType: 'signature',
    level: 'success',
    actorId: 'agt-soroban-relayer',
    actorName: 'Soroban Relayer Sentinel',
    actorType: 'agent',
    summary: 'Signed Soroban Smart Contract invocation for batch settlement',
    details: 'Invoked contract CC3K...89FA method execute_settlement with 450.00 USDC.',
    project: 'Core Protocol',
    amount: 450,
    asset: 'USDC',
    xdrHash: 'AAAAAgAAAAC3a...8f9a2e',
    rawPayload: {
      transactionHash: '5c77fc346943f56e10fc3666f4640211d721c1754886f107aac9fa696897662e',
      feeStroops: 100,
      sequenceNumber: '14820491',
      contractId: 'CC3K9X728N490218389FA',
      function: 'execute_settlement',
      args: ['USDC', 4500000000n.toString()],
    },
  },
  {
    id: 'evt-1002',
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    eventType: 'policy_change',
    level: 'warning',
    actorId: 'usr-admin-alex',
    actorName: 'Alex Rivera (Admin)',
    actorType: 'user',
    summary: 'Updated daily spend cap for Growth & Marketing department',
    details: 'Increased maximum daily velocity limit from 10,000 USDC to 25,000 USDC.',
    project: 'Governance',
    rawPayload: {
      previousPolicy: { dailyCap: 10000, currency: 'USDC' },
      newPolicy: { dailyCap: 25000, currency: 'USDC' },
      reason: 'Marketing campaign scaling approval',
      approvedBy: 'Alex Rivera',
    },
  },
  {
    id: 'evt-1003',
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    eventType: 'key_rotation',
    level: 'info',
    actorId: 'agt-sweep-bot',
    actorName: 'Auto-Sweep Treasury Bot',
    actorType: 'agent',
    summary: 'Rotated API Secret Key for Horizon RPC Endpoint',
    details: 'Automated 30-day credential rotation completed successfully without downtime.',
    project: 'Security & Vault',
    rawPayload: {
      keyId: 'key-horizon-prod-02',
      rotationPeriodDays: 30,
      status: 'active',
      previousKeyRevoked: true,
    },
  },
  {
    id: 'evt-1004',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    eventType: 'action',
    level: 'error',
    actorId: 'agt-amm-arb',
    actorName: 'Soroban DEX Arbitrageur',
    actorType: 'agent',
    summary: 'Arbitrage transaction rejected: Slippage threshold exceeded',
    details: 'Trade path XLM->USDC failed simulation with 2.4% slippage (max allowed: 0.5%).',
    project: 'DeFi Liquidity',
    amount: 1200,
    asset: 'XLM',
    rawPayload: {
      expectedOutput: '150.00 USDC',
      simulatedOutput: '146.40 USDC',
      maxSlippageBps: 50,
      actualSlippageBps: 240,
      status: 'simulation_failed',
    },
  },
  {
    id: 'evt-1005',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    eventType: 'approval',
    level: 'success',
    actorId: 'usr-finance-elena',
    actorName: 'Elena Rostova (Finance)',
    actorType: 'user',
    summary: 'Approved high-value multi-sig disbursement request',
    details: 'Multi-sig threshold reached (2 of 3 signers approved 50,000 XLM transfer).',
    project: 'Treasury Operations',
    amount: 50000,
    asset: 'XLM',
    rawPayload: {
      requestId: 'req-multisig-882',
      requiredSignatures: 2,
      currentSignatures: 2,
      signers: ['GABC...1234', 'GDEF...5678'],
      executionStatus: 'queued',
    },
  },
  {
    id: 'evt-1006',
    timestamp: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    eventType: 'budget_cap',
    level: 'warning',
    actorId: 'agt-nim-briefing',
    actorName: 'Nvidia NIM Analyst Agent',
    actorType: 'agent',
    summary: 'Approaching monthly token allocation ceiling (92% reached)',
    details: 'Agent has consumed 92,000 ASTRO out of 100,000 ASTRO monthly budget cap.',
    project: 'AI Inference',
    amount: 92000,
    asset: 'ASTRO',
    rawPayload: {
      budgetCap: 100000,
      consumed: 92000,
      alertThresholdPercent: 90,
      autoReplenish: false,
    },
  },
];
